defaults: &defaults
  working_directory: /srv/jekyll/
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: jekyll/jekyll:pages
    environment:
      BUNDLE_PATH: /srv/jekyll/vendor/bundle
    steps:
      - checkout
      - run:
          name: Jekyll build
          command: jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
